# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d7f802f7f90c97ac9e2c478071a0dcff7c9c1e0498a76addc66ceb827bd6ecc03e51f27ccc74becda607c81ec016e9e73d617960dc5236b7f5c8432e826a73

test:
  secret_key_base: 8fa6d3461e16ef6d38954ace96d52bc608d59df592fb12254d3e65ec0400268173bd27f4a2b7fdd44a915f56f02de338e78ae41089c38c5248a120c375c071a2

# Do not keep  secrets in the repository,
# instead read values from the environment.
:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
